version: '3'

services:
  web:
    container_name: debio-frontend
    image: debionetwork/debio-frontend
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8082:80
    networks:
      debio:
        ipv4_address: 172.27.1.6
        aliases:
          - debio-frontend

networks:
  debio:
    external: true
