{{- if .Values.config.recaptchaSiteKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-frontend.recaptchaSiteKeySecretName" . }}
type: Opaque
data:
  recaptchaSiteKey: {{ .Values.config.recaptchaSiteKey | b64enc }}

---
{{- end }}
{{- if .Values.config.debioEscrowETHAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-frontend.debioEscrowETHAddressSecretName" . }}
type: Opaque
data:
  debioEscrowETHAddress: {{ .Values.config.debioEscrowETHAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.devDebioEscrowETHAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-frontend.devDebioEscrowETHAddressSecretName" . }}
type: Opaque
data:
  devDebioEscrowETHAddress: {{ .Values.config.devDebioEscrowETHAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.daiContractAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-frontend.daiContractAddressSecretName" . }}
type: Opaque
data:
  daiContractAddress: {{ .Values.config.daiContractAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.debioApiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-frontend.debioApiKeySecretName" . }}
type: Opaque
data:
  debioApiKey: {{ .Values.config.debioApiKey | b64enc }}

{{- end }}