name: Benchmark automation

on:
  issue_comment:
    types:
    - created

concurrency:
  group: benchmark-automation

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          export_default_credentials: true
      - name: start runner
        run: gcloud compute instances start github-runner-debio-node-benchmark --zone=australia-southeast1-b

  self-host:
    runs-on: [self-hosted]
    needs: start-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: benchmarking
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '/benchmark'}}
        run: echo "Benchmark running!"

  stop-runner:
    runs-on: ubuntu-latest
    needs: self-host
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          export_default_credentials: true
      - name: stop runner
        run: gcloud compute instances stop github-runner-debio-node-benchmark --zone=australia-southeast1-b
