name: Benchmark automation

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

concurrency:
  group: benchmark-automation

jobs:
  self-host:
    runs-on: [self-hosted, benchmark]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pull Request Comment Trigger
        uses: Khan/pull-request-comment-trigger@1.0.0
        id: check
        with:
          trigger: '/benchmark'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: benchmarking
        if: steps.check.outputs.triggered == 'true'
        run: 'Benchmark running!'
