name: Main automation

on:
  push:
    branches:
      - main

concurrency:
  group: main-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      date: ${{ steps.build-info.outputs.date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y%m%d')"

  pull-request:
    runs-on: ubuntu-latest
    needs: [compute-build-info]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Remove directory and file
        shell: bash
        run: |
          rm -rf benchmark
      - name: Add directory and file
        shell: bash
        run: |
          mkdir -p benchmark
          touch benchmark/benchmark.text

          tee -a benchmark/benchmark.text <<EOF
          ${{ needs.compute-build-info.outputs.sha_short }}
          EOF
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Benchmark
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: benchmark
          delete-branch: true
          title: "Update Benchmark"
          body: |
            Update benchmark

            :crown: *An automated PR*
          labels: benchmark
          assignees: meziaris
          reviewers: meziaris
          draft: false
