name: Main automation

on:
  push:
    branches:
      - main

concurrency:
  group: main-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      date: ${{ steps.build-info.outputs.date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y%m%d')"

  pull-request:
    runs-on: ubuntu-latest
    needs: [compute-build-info,changes]
    steps:
      - uses: actions/checkout@v2
      - name: Add directory and file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.secrets.outputs.SSH_HOST }}
          username: ${{ steps.secrets.outputs.SSH_USERNAME }}
          key: ${{ steps.secrets.outputs.SSH_KEY }}
          port: ${{ steps.secrets.outputs.SSH_PORT }}
          script: |
            mkdir -p test-dir
            touch test-dir/test.text
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: ":crown: *An automated PR*"
          pr_template: ".github/pull_request_template.md"
          pr_reviewer: "irmannmal,agustinustheo,hilyds,meziaris"
          pr_assignee: "debio-devops"
          pr_label: "auto-pr"
          github_token: ${{ secrets.GITHUB_TOKEN }}
